name: Docker Build
on:
  push:
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: pldi_ae_container:latest
          load: true
          platforms: linux/amd64

      - name: Save docker image
        run: |
          docker save pldi_ae_container:latest | gzip > pldi_ae_container.tar.gz

      - name: Upload docker image
        uses: actions/upload-artifact@v2
        with:
          name: pldi_ae_container
          path: pldi_ae_container.tar.gz
